export * from "./IDeeplResponse"
export * from "./IDictionaryEntry"
export * from "./IGoogleResponse"
export * from "./ISentenceSource"
export * from "./ISources"
export * from "./ITranslation"
export * from "./ResourceState"
export * from "./UiColorVariant"
