export * from "./DeeplResponse";
export * from "./DictionaryEntry";
export * from "./GoogleResponse";
export * from "./SentenceSource";
export * from "./Source";
export * from "./Sources";
export * from "./Translation";
export * from "./ResourceState";
export * from "./UiColorVariant";
